server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.56.100
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4GHk3haNfDH58xc65bHj # 你自己的accessKeyId
    accessKeySecret: nIKmfJRT8FOLhwOnjUyzcHoReg0ZFb # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称